// Interface copy only. Do not add note contents, paths or AI prompts here.
module.exports = {
  '思考过程': 'Thinking process',
  '思考中…': 'Thinking…',
  '已结束': 'Finished',
  '本次生成尚未输出正文。': 'This attempt has not produced an answer yet.',
  '生成达到模型服务的长度上限，回答未完成。': 'Generation reached the model service length limit. The answer is incomplete.',
  "已停止生成。": "Generation stopped.",
  "连接中断，回答尚未完成，请重试。": "Connection interrupted. The answer is incomplete; try again.",
  "响应超时，请重试。": "Response timed out. Try again.",
  "回答尚未完成，请重试。": "The answer is incomplete. Try again.",
  "无法更新官方价格，请稍后重试。": "Could not update official prices. Try again later.",
  "学习助手语言": "Assistant language",
  "切换学习助手语言": "Switch assistant language",
  "资料生成语言": "Learning material language",
  "用于助手侧边栏与 AI 解释，可与资料生成语言分别设置；已有回答保留原文。": "Applies to the assistant sidebar and explanations, independently of generated materials. Existing answers retain their language.",
  "人民币费用": "Cost in CNY",
  "按官方人民币价格、缓存用量与高峰/空闲时段估算；每次调用保存当时的价格。": "Estimated from official CNY rates, cache usage and peak/off-peak periods. Each call saves its price snapshot.",
  "更新官方价格": "Update official prices",
  "官方价格已更新。": "Official prices updated.",
  "约 ¥{0}": "About ¥{0}",
  "费用暂不可算": "Cost unavailable",
  "高峰价格": "Peak rate",
  "空闲价格": "Off-peak rate",
  "{0} · 价格更新于 {1}": "{0} · Prices verified {1}",
  "每百万 tokens：命中 ¥{0} · 未命中 ¥{1} · 输出 ¥{2}": "Per 1M tokens: cached ¥{0} · uncached ¥{1} · output ¥{2}",
  "官方价格": "Official pricing",
  "按 API 用量估算，实际扣费以 DeepSeek 账单为准。": "Estimated from API usage. Actual charges are shown on your DeepSeek bill.",
  "缺少用量、历史价格或自定义接口的价格，无法准确计算。": "Missing usage, historical rates or custom endpoint prices prevent a reliable estimate.",
  "正在生成…": "Generating…",
  "回答未完成": "Incomplete answer",
  "停止": "Stop",
  "输入": "Input",
  "输出": "Output",
  "推理": "Reasoning",
  "缓存命中": "Cache hit",
  "缓存未命中": "Cache miss",

  "解释选文、梳理概念，或继续追问。": "Explain a passage, explore a concept, or ask a follow-up.",
  "选文附件": "Selected passage",
  "01 / COURSE INITIALIZATION": "01 / COURSE SETUP",
  "保存": "Save",
  "请填写名称": "Enter a name.",
  "完成记录": "Completion record",
  "预计用时 {0} 分钟 · 记录实际情况，帮助后续安排更准确。": "Estimated: {0} min. Record the outcome to improve future plans.",
  "记录实际完成情况，帮助后续安排更准确。": "Record the outcome to improve future plans.",
  "完成情况": "Outcome",
  "按时完成": "On time",
  "按计划完成": "Completed as planned",
  "未按时完成": "Completed late",
  "完成了，但比计划晚": "Completed after the planned time",
  "未完成": "Unfinished",
  "保留在待办中": "Keep in tasks",
  "实际完成日期": "Completion date",
  "实际用时": "Time spent",
  "预计 {0} 分钟": "Estimated: {0} min",
  "分钟（可选）": "Minutes (optional)",
  "取消": "Cancel",
  "保存记录": "Save record",
  "请选择今天或更早的完成日期": "Choose today or an earlier date.",
  "保存失败：{0}": "Could not save: {0}",
  "告诉我你要完成哪些事，可以一次说多个。说明、DDL、课程或讲次会分别记录；没提到的字段会留空。": "Tell me what you need to do. Include a deadline, course or lesson if relevant. You can add several tasks at once.",
  "告诉我每周哪些日子、什么时间可以学习。我会整理成周时段供你核对；点击应用后才会保存，并据此更新滚动日程。": "Tell me which days and times you can study each week. Review the weekly schedule; it is saved and applied to the rolling schedule only after you confirm.",
  "设置可学习时间与休息安排": "Set study availability and rest periods",
  "告诉我每周可学习的时间，也可以说哪些日期或时段休息。我会整理成可核对的安排；点击应用后才保存并更新滚动日程。": "Tell me when you can study each week and which dates or times you want to reserve for rest. Review the plan; it is saved and applied to the rolling schedule only after you confirm.",
  "例如：工作日晚上 7 点到 10 点；下周六全天休息；每周三下午 2 点到 5 点休息。你可以继续对话修改或取消。": "For example: weekdays, 7–10 pm; next Saturday off all day; Wednesdays, 2–5 pm off. Continue the chat to make changes or remove rules.",
  "DEEPSEEK · 时间安排": "DEEPSEEK · AVAILABILITY & REST",
  "可学习时间与休息安排对话": "Availability and rest conversation",
  "休息安排": "Rest periods",
  "暂无额外休息安排": "No additional rest periods",
  "全天休息": "Rest all day",
  "{0}–{1} 休息": "Rest {0}–{1}",
  "例如：每周一到周五晚上 7 点到 10 点可以学习，10 月 10 日休息…": "For example: weekdays, 7–10 pm; October 10 off…",
  "描述可学习时间和休息安排": "Describe study availability and rest periods",
  "应用时间安排": "Apply schedule settings",
  "可学习时间与休息安排已更新，滚动日程已同步。": "Availability and rest periods are updated, and the rolling schedule is synced.",
  "午餐": "Lunch",
  "晚餐": "Dinner",
  "系统日程": "System schedule",
  "系统日程 · 用餐时间": "System schedule · meals",
  "系统用餐安排 · 无需标记完成": "System meal period · no completion status",
  "此草案缺少系统用餐安排，请舍弃并重新生成。": "This draft does not include system meal periods. Discard it and generate a new draft.",
  "确认后将替换这 7 天内此前由 AI 安排的学习时段和系统用餐安排；手动录入的日程会保留。": "Confirming replaces AI study periods and system meal periods for these 7 days. Manually entered items are kept.",
  "请先添加待办或完成待复习讲次；当前没有可排的任务或用餐时间。": "Add a task or an unlocked review first; there are no tasks or upcoming meal periods to schedule.",
  "AI 返回的日程或用餐安排格式无效。": "AI returned an invalid schedule or meal-period response.",
  "AI 返回的系统用餐时段无效。": "AI returned an invalid system meal period.",
  "AI 安排了不需要的{0}时段。": "AI added an unrequested {0} period.",
  "{0}只能安排一次。": "Only one {0} period can be scheduled per day.",
  "{0}须在指定时段内安排一小时。": "{0} must be one hour and fit within its allowed window.",
  "{0}与「{1}」冲突。": "{0} conflicts with “{1}”.",
  "{0}与学习安排「{1}」冲突。": "{0} conflicts with study item “{1}”.",
  "{0}与另一用餐时段冲突。": "{0} conflicts with another meal period.",
  "未安排 {0} 的{1}。": "No {1} period was scheduled for {0}.",
  "学习安排「{0}」与{1}冲突。": "Study item “{0}” conflicts with {1}.",
  "时间安排已在其他窗口中更新，请重新打开设置。": "Schedule settings changed in another window. Reopen the settings.",
  "时间安排已保存，但滚动日程更新失败：{0}": "Schedule settings were saved, but the rolling schedule could not be updated: {0}",
  "该时段已标记为休息，不能安排内容": "This time is marked for rest and cannot be scheduled.",
  "AI 返回的休息安排格式不完整，请再试一次。": "AI returned an incomplete rest-period draft. Try again.",
  "AI 返回的第 {0} 条休息安排日期无效，请再试一次。": "AI returned an invalid rest date at position {0}. Try again.",
  "AI 返回的第 {0} 条休息安排星期无效，请再试一次。": "AI returned an invalid rest weekday at position {0}. Try again.",
  "AI 返回的第 {0} 条休息时段无效，请再试一次。": "AI returned an invalid rest period at position {0}. Try again.",
  "DEEPSEEK · 可学习时间": "DEEPSEEK · STUDY AVAILABILITY",
  "设置可学习时间": "Set study availability",
  "例如：工作日晚上 7 点到 10 点，周六上午 9 点到 12 点。你可以继续对话调整星期和时间。": "For example: weekdays, 7–10 pm, and Saturday, 9 am–noon. Continue the chat to adjust days and times.",
  "可学习时间对话": "Study availability conversation",
  "周时段预览": "Weekly time windows",
  "AI 已整理 · 请核对后应用": "Prepared by AI · Review before applying",
  "AI 修改后会显示在这里": "AI changes will appear here",
  "未设置": "Not set",
  "至少保留一个每周可学习时段，才能安排滚动日程。": "Keep at least one weekly study window to schedule tasks.",
  "例如：周一到周五晚上 7 点到 10 点，周末先不安排学习…": "For example: weekdays, 7–10 pm; no study on weekends…",
  "描述每周可学习时间": "Describe your weekly study availability",
  "先在设置中填写统一的 DeepSeek API Key。": "Add the shared DeepSeek API key in settings first.",
  "预览不会自动保存；确认后才应用并更新未来 7 天的滚动日程。": "The preview is not saved automatically. Confirm to apply it and update the next 7 days.",
  "应用可学习时间": "Apply study availability",
  "暂时无法整理可学习时间，请重试。": "Could not prepare study availability. Try again.",
  "可学习时间已在其他窗口中更新，请重新打开设置。": "Study availability changed in another window. Reopen the settings.",
  "可学习时间已更新，滚动日程已同步。": "Study availability is updated and the rolling schedule is synced.",
  "可学习时间已保存，但滚动日程更新失败：{0}": "Study availability was saved, but the rolling schedule could not be updated: {0}",
  "AI 返回的可学习时间格式不完整，请再试一次。": "AI returned an incomplete study availability draft. Try again.",
  "AI 返回的第 {0} 个可学习时段无效，请再试一次。": "AI returned an invalid study window at position {0}. Try again.",
  "AI 返回的可学习时段有重叠，请让 AI 调整后再试。": "AI returned overlapping study windows. Ask it to adjust them and try again.",
  "AI 没有返回可核对的可学习时间。": "AI did not return study availability to review.",
  "DEEPSEEK · 待办录入": "DEEPSEEK · TASK INTAKE",
  "核对 {0} 项待办": "Review {0} tasks",
  "对话添加待办": "Add tasks with AI",
  "逐项检查或删除。确认后才会一起加入待办。": "Review or remove each task before adding them.",
  "可以一次说多个事项；只提取对话中明确的信息。": "Describe several tasks at once. Only details you provide will be recorded.",
  "待办录入对话": "Task intake conversation",
  "你": "You",
  "当前草稿 · {0} 项": "Draft · {0} tasks",
  "未命名事项": "Untitled task",
  "未设置 DDL": "No deadline",
  "未关联课程": "No course linked",
  "例如：周五 23:59 前提交机器学习作业第 2 题…": "For example: submit question 2 of the ML assignment by Friday, 23:59…",
  "请先在插件设置中填写 DeepSeek API Key": "Add a DeepSeek API key in settings first.",
  "描述要添加的待办": "Describe your tasks",
  "正在整理…": "Organizing…",
  "发送": "Send",
  "⌘ / Ctrl + Enter 发送": "⌘ / Ctrl + Enter to send",
  "核对 {0} 项 →": "Review {0} tasks →",
  "请先在 Learning Hub 设置中填写 DeepSeek API Key。": "Add a DeepSeek API key in Learning Hub settings first.",
  "事项 {0}": "Task {0}",
  "删除此项": "Remove",
  "需要完成的事项": "Task name",
  "详细说明（可选）": "Description (optional)",
  "DDL 日期（可选）": "Deadline date (optional)",
  "DDL 时间（可选）": "Deadline time (optional)",
  "关联课程（可选）": "Course (optional)",
  "不关联课程": "No course",
  "关联讲次（可选）": "Lesson (optional)",
  "不关联讲次": "No lesson",
  "在最近事项中置顶": "Pin in recent tasks",
  "＋ 新增一项": "＋ Add task",
  "保存前请检查 AI 提取的内容。": "Check the AI draft before saving.",
  "返回对话": "Back to chat",
  "确认添加 {0} 项": "Add {0} tasks",
  "已添加 {0} 项待办": "Added {0} tasks.",
  "添加待办失败：{0}": "Could not add tasks: {0}",
  "正在提取文件文字": "Reading file text",
  "等待 Codex": "Waiting for Codex",
  "连接 Codex": "Connecting to Codex",
  "启动分析": "Starting analysis",
  "正在分析 Syllabus": "Analyzing syllabus",
  "正在接收结果": "Receiving result",
  "解析完成": "Analysis complete",
  "解析失败": "Analysis failed",
  "正在处理": "Processing",
  "{0} · {1} 秒{2}": "{0} · {1}s{2}",
  " · 已接收 {0} 字符": " · {0} characters received",
  "Codex 正在分析课程结构…": "Codex is analyzing the course structure…",
  "核对课程概览": "Review course overview",
  "解析 Syllabus": "Analyze syllabus",
  "来源文件": "Source file",
  "解析没有完成": "Analysis did not finish",
  "正在整理整门课的信息": "Organizing course information",
  "原文件已保存；确认前不会写入课程概览。": "Source saved. Review and confirm before updating the overview.",
  "关闭": "Close",
  "重新解析": "Analyze again",
  "确认写入课程概览": "Save course overview",
  "Course Initial 已写入课程概览": "Course overview saved.",
  "再检查一下": "Review again",
  "保存失败，请重试": "Could not save. Try again.",
  "编辑作业信息": "Edit assignment",
  "上传并存档作业": "Upload assignment",
  "已选择 {0} 个文件：{1}{2}": "{0} files selected: {1}{2}",
  "作业名称": "Assignment name",
  "截止日期（可选）": "Due date (optional)",
  "设置截止日期后，会自动加入本课程待办并进入 7 天滚动日程；清除日期会取消联动。": "A due date adds a linked task to the 7-day schedule. Clearing it removes the link.",
  "难度（可修正 AI 结果）": "Difficulty (editable)",
  "基础": "Basic",
  "中等": "Intermediate",
  "较难": "Advanced",
  "涉及知识点（可修正 AI 结果）": "Topics (editable)",
  "例如：矩阵可逆、秩、特征值": "For example: invertibility, rank, eigenvalues",
  "保存后会自动整理题目并分析难度与知识点。": "Saving starts AI analysis of questions, difficulty and topics.",
  "关联讲次": "Linked lesson",
  "整个课程 / 稍后选择": "Whole course / choose later",
  "保存信息": "Save changes",
  "保存作业": "Save assignment",
  "请填写作业名称": "Enter an assignment name.",
  "保存作业失败，请重试": "Could not save the assignment. Try again.",
  "编辑 Lab Session": "Edit lab",
  "上传 Lab Session 课件": "Upload lab materials",
  "已选择 {0} 个文件：{1}": "{0} files selected: {1}",
  "Lab Session 名称": "Lab name",
  "整个课程": "Whole course",
  "保存并解析": "Save and analyze",
  "请填写 Lab Session 名称": "Enter a lab name.",
  "Lab Session 保存失败：{0}": "Could not save the lab: {0}",
  "预习": "Preview",
  "回忆": "Recall",
  "复习 {0}": "Review {0}",
  "作业与 Lab Session · {0}": "Assignments & labs · {0}",
  "讲次": "Lessons",
  "课程概览 · {0}": "Course overview · {0}",
  "完整日程": "Schedule",
  "待办事项": "Tasks",
  "学习复盘": "Learning review",
  "草稿本": "Drafts",
  "学习主页": "Learning home",
  "日程": "Schedule",
  "待办": "Tasks",
  "复盘": "Review",
  "总览": "Overview",
  "学习空间": "Learning space",
  "返回个人主页": "Back to home",
  "课程": "Courses",
  "课程概览": "Course overview",
  "课程大纲": "Syllabus",
  "课程文件": "Course files",
  "作业与 Lab Session": "Assignments & labs",
  "间隔复习": "Spaced review",
  "上传课件": "Upload slides",
  "工作台": "Workspace",
  "个人主页": "Home",
  "{0}课程": "{0} courses",
  "本学期": "This semester",
  "这个学期还没有课程。": "No courses in this semester yet.",
  "其他空间": "Other spaces",
  "课外学习": "Self study",
  "{0} 讲课程资料": "{0} lessons",
  "{0} 门课程": "{0} courses",
  "打开课程总目录": "Open course index",
  "打开学习空间": "Open learning space",
  "新建草稿": "New draft",
  "打开学习助手": "Open learning assistant",
  "打开学习主页": "Open learning home",
  "新建时间草稿": "New timestamped draft",
  "为当前时间草稿生成标题": "Generate a title for this draft",
  "打开完整日程": "Open schedule",
  "打开学习复盘": "Open learning review",
  "打开学习助手侧边栏": "Open learning assistant sidebar",
  "请填写学期名称": "Enter a semester name.",
  "学期「{0}」已经存在": "Semester “{0}” already exists.",
  "已创建学期「{0}」": "Created semester “{0}”.",
  "请先选择学期": "Select a semester first.",
  "课程代码格式示例：COMP 1002": "Course code example: COMP 1002",
  "请填写课程名称": "Enter a course name.",
  "「{0}」已经在{1}中": "“{0}” is already in {1}.",
  "已将现有课程「{0}」加入{1}；原笔记与学习记录会继续共用。": "Added “{0}” to {1}. Existing notes and learning records are shared.",
  "已在{0}创建课程「{1}」": "Created “{1}” in {0}.",
  "Syllabus 上传失败：{0}": "Could not upload the syllabus: {0}",
  "已保存 {0} 份 Lab Session 课件{1}": "Saved {0} lab files{1}",
  "，{0} 份未导入": "; {0} files were not imported",
  "Lab Session 没有成功导入可解析文件": "No readable lab files were imported.",
  "Lab Session 已保存；解析失败：{0}": "Lab saved; analysis failed: {0}",
  "Lab Session 不存在": "Lab not found.",
  "《{0}》已解析完成。": "Analysis of “{0}” complete.",
  "已删除《{0}》；原文件已移入 Obsidian 回收站。": "Deleted “{0}”. Source files moved to Obsidian trash.",
  "已保存 {0} 个文件，{1} 个导入失败": "Saved {0} files; {1} imports failed.",
  "已归档 {0} 个作业文件": "Archived {0} assignment files.",
  "作业已保存；AI 分析失败：{0}": "Assignment saved; AI analysis failed: {0}",
  "作业待办已更新，日程稍后可手动刷新。": "Linked task updated. Refresh the schedule when ready.",
  "正在提取作业文字": "Reading assignment text",
  "正在连接 Codex": "Connecting to Codex",
  "正在提交任务": "Submitting task",
  "Codex 正在分析": "Codex is analyzing",
  "Codex 正在思考": "Codex is thinking",
  "Codex 正在返回结果": "Codex is returning the result",
  "{0} · 已用时 {1}{2}": "{0} · Elapsed {1}{2}",
  "等待 Codex 提供思考摘要…": "Waiting for a reasoning summary…",
  "《{0}》的题目、难度与知识点已整理完成。": "Questions, difficulty and topics for “{0}” are ready.",
  "先在作业档案中补充涉及的知识点": "Add topics to the assignment first.",
  "本轮尚未开放或已经完成": "This review round is locked or complete.",
  "这份作业已用于本轮复习题": "This assignment has already been used in this round.",
  "尚无此页面：": "Page not found: ",
  "学习助手侧边栏迁移失败，请重新打开。": "Could not move the assistant sidebar. Reopen it.",
  "无法打开右侧学习助手。": "Could not open the assistant sidebar.",
  "Google Calendar 已同步 {0} 项日程。": "Synced {0} Google Calendar events.",
  "Google Calendar 同步失败：{0}": "Google Calendar sync failed: {0}",
  "{0} · {1} 门课程。日程、待办和学习进度都在这里。": "{0} · {1} courses. Your schedule, tasks and progress.",
  "{0}{1}从今天最重要的事开始。": "{0}{1}Start with today's priorities.",
  "{0} 项待办已到期。": "{0} tasks are due. ",
  "{0} 个讲次待复习。": "{0} lessons need review. ",
  "日程安排": "Upcoming schedule",
  "最近 3 件": "Next 3 events",
  "近期没有需要处理的日程。": "No upcoming events need attention.",
  "查看完整日程 →": "View schedule →",
  "AI 安排 7 天": "Plan 7 days with AI",
  "今日待办": "Today's tasks",
  "{0} 项": "{0} tasks",
  "今天没有需要完成的待办。": "No tasks due today.",
  "查看全部待办 →": "View all tasks →",
  "＋ 添加待办": "＋ Add task",
  "课程总览": "Courses",
  "{0} 门课程 · {1} · 点击进入": "{0} courses · {1} · Open a course",
  "学期": "Semester",
  "打开 {0}": "Open {0}",
  "{0} · {1} 讲纳入范围": "{0} · {1} lessons in scope",
  "当前学期还没有课程。可在插件设置中创建课程。": "No courses yet. Create one in settings.",
  "只统计已纳入范围的讲次；待复习为已解锁轮次。": "Counts include lessons in scope and unlocked review rounds.",
  "查看课程总目录 ↗": "Open course index ↗",
  "最近事项": "Recent tasks",
  "{0} 项置顶 · 按 DDL 排序": "{0} pinned · By deadline",
  "暂无设置 DDL 或置顶的事项。": "No pinned tasks or deadlines.",
  "已完成 · 置顶": "Completed · Pinned",
  "置顶": "Pinned",
  "项目与论文": "Projects & papers",
  "课外学习 →": "Self study →",
  "论文阅读：尚未建立统一入口": "Paper reading has no shared entry yet.",
  "创建草稿失败：{0}": "Could not create a draft: {0}",
  "只为 Draft 文件夹中仍以时间命名的草稿生成标题": "Only timestamped drafts in the Draft folder can be renamed.",
  "空草稿保持时间标题；写入内容后再生成标题": "Empty drafts keep their timestamp. Add content first.",
  "请在 Learning Hub 设置中填写统一的 DeepSeek API Key": "Add your shared DeepSeek API key in Learning Hub settings.",
  "草稿已命名：{0}": "Draft renamed: {0}",
  "草稿命名失败：{0}，已保留原名": "Could not rename draft: {0}. Original name kept.",
  "接口错误": "API error",
  "按创建时间倒序": "Newest first",
  "Draft 文件夹目前还没有 Markdown 草稿。": "No Markdown drafts in the Draft folder.",
  "＋ 新建草稿": "＋ New draft",
  "草稿保存到 Draft 文件夹后，会自动出现在这里。": "Drafts saved in the Draft folder appear here.",
  "标题": "Title",
  "创建时间": "Created",
  "{0}，创建于 {1}": "{0}, created {1}",
  "今天": "Today",
  "明天": "Tomorrow",
  "昨天": "Yesterday",
  "全天": "All day",
  "固定日程": "Fixed event",
  "学习安排": "Study session",
  "逾期未完成": "Overdue",
  "更新「{0}」的完成状态": "Update completion of “{0}”",
  "无 DDL": "No deadline",
  "记录「{0}」的完成情况": "Record completion of “{0}”",
  "个人": "Personal",
  "记录状态": "Record outcome",
  "取消置顶": "Unpin",
  "编辑": "Edit",
  "{0} 全天": "{0} all day",
  "固定安排": "Fixed event",
  "可调整": "Flexible",
  "参加": "Attend",
  "编辑待办": "Edit task",
  "删除待办": "Delete task",
  "删除此待办？": "Delete this task?",
  "删除后，与此待办关联的日程安排会一并移除；历史完成记录会保留。": "Associated schedule items will also be removed. Completion history will be kept.",
  "已删除待办《{0}》。": "Deleted task “{0}”.",
  "待办已删除，但日程更新失败，可稍后手动更新。": "Task deleted, but the schedule could not be refreshed. Try again later.",
  "添加待办": "Add task",
  "DDL（可选）": "Deadline (optional)",
  "请填写事项名称": "Enter a task name.",
  "填写 DDL 时间前，请先选择日期": "Choose a date before setting a deadline time.",
  "请选择 1–30 项待办": "Add between 1 and 30 tasks.",
  "请填写第 {0} 项的名称": "Enter a name for task {0}.",
  "第 {0} 项的 DDL 日期无效": "Invalid deadline date for task {0}.",
  "第 {0} 项的 DDL 时间无效": "Invalid deadline time for task {0}.",
  "待办已添加，日程更新失败，可稍后手动更新。": "Task added. Schedule update failed; refresh it later.",
  "添加提醒": "Add reminder",
  "事项": "Task",
  "时间": "Time",
  "来源": "Source",
  "邮件标题 / 课程通知 / 手动": "Email / course notice / manual",
  "安排时间段": "Schedule a time block",
  "要做什么": "Activity",
  "开始": "Start",
  "结束": "End",
  "请选择同一天内有效的开始和结束时间": "Choose a valid start and end on the same day.",
  "与「{0}」冲突，请换一个时间。": "Conflicts with “{0}”. Choose another time.",
  "已确认完成课堂学习": "Class learning confirmed.",
  "确认课堂学习": "Confirm class learning",
  "确认你已经在唯一主笔记中完成本讲学习与课堂补充。复习日期将按实际完成日期计算。": "Confirm that this lesson and class notes are complete. Reviews use your actual completion date.",
  "确认完成": "Confirm completion",
  "已安排第 1 / 7 / 21 天复习": "Reviews scheduled for days 1, 7 and 21.",
  "显示接下来 7 天的日程；逾期未完成事项单独保留。Tut / Lab 默认不参加，可在下方选择。": "Next 7 days, plus overdue events. Tutorials and labs are optional; choose attendance below.",
  "AI 生成 7 天草案": "Draft 7 days with AI",
  "更新滚动日程": "Refresh schedule",
  "已新增 {0} 个学习时段。": "Added {0} study sessions.",
  "现有安排已是最新。": "Schedule is up to date.",
  "更新失败：{0}": "Update failed: {0}",
  "＋ 安排时间段": "＋ Add time block",
  "同步 Google Calendar": "Sync Google Calendar",
  "返回主页": "Back to home",
  "Google Calendar 上次同步失败：{0}；已显示缓存日程。": "Last Google Calendar sync failed: {0}. Showing cached events.",
  "Google Calendar · {0} 项 · 更新于 {1}": "Google Calendar · {0} events · Updated {1}",
  "Google Calendar 正在等待首次同步": "Waiting for the first Google Calendar sync",
  "有 {0} 项任务尚未找到满足截止时间的空档，请检查可用时间或 DDL。": "No slot before the deadline for {0} tasks. Check availability or deadlines.",
  "{0} — {1} · 共 {2} 项": "{0} — {1} · {2} events",
  "{0} 项 · 完成后自动移出": "{0} events · Removed on completion",
  "这 7 天没有已确定的日程。": "No confirmed events in these 7 days.",
  "{0} · 暂无已确定日程": "{0} · No confirmed events",
  "{0} — {1} · 暂无已确定日程": "{0} — {1} · No confirmed events",
  "正在生成日程草案…": "Drafting schedule…",
  "正在安排未来 7 天": "Planning the next 7 days",
  "读取日程": "Read schedule",
  "AI 排程": "AI planning",
  "检查冲突": "Check conflicts",
  "正在同步日历并读取忙碌时段…": "Syncing calendar and checking busy times…",
  "正在整理任务与可用时间…": "Preparing tasks and available times…",
  "等待 Codex 任务开始…": "Waiting for Codex to start…",
  "正在连接 Codex…": "Connecting to Codex…",
  "正在提交日程规划…": "Sending schedule request…",
  "Codex 正在安排任务…": "Codex is scheduling tasks…",
  "Codex 正在分析任务优先级…": "Codex is weighing task priorities…",
  "Codex 正在返回日程草案…": "Codex is returning the schedule draft…",
  "正在检查草案中的时间冲突…": "Checking the draft for time conflicts…",
  "AI 的进度摘要会在生成过程中更新。": "The AI progress summary will update as it works.",
  "请先添加待办或完成待复习讲次；没有真实任务可供排程。": "Add tasks or unlock a review first. There is nothing to schedule yet.",
  "AI 日程草案已生成，请核对后采用。": "Schedule draft ready. Review it before applying.",
  "草案有时间冲突，请检查或重新生成。": "Draft has conflicts. Check it or generate again.",
  "日程草案未生成：{0}": "Could not draft schedule: {0}",
  "待确认的 AI 日程": "Review AI schedule",
  "AI 未提供安排摘要。": "No summary provided.",
  "冲突：{0}": "Conflict: {0}",
  "提醒：{0}": "Note: {0}",
  "未安排：{0} · {1}": "Unscheduled: {0} · {1}",
  "确认并应用日程": "Apply schedule",
  "确认 AI 日程": "Confirm AI schedule",
  "确认后将替换这 7 天内此前由 AI 安排的时间段；手动录入的日程会保留。": "This replaces AI time blocks in these 7 days. Manual events are kept.",
  "确认应用": "Apply",
  "日程已变化：{0}": "Schedule has changed: {0}",
  "舍弃草案": "Discard draft",
  "写下事项与可选说明、DDL；系统估算用时并纳入未来 7 天日程。": "Add tasks, descriptions and deadlines. Time estimates feed the next 7 days.",
  "和 AI 对话添加": "Add with AI",
  "查看复盘 →": "View learning review →",
  "待完成": "Unfinished",
  "已完成": "Completed",
  "当前没有待办。": "No unfinished tasks.",
  "尚无完成记录。": "No completion records yet.",
  "回看这一年的学习节奏，点选日期查看当天完成的事。": "Explore your learning activity. Select a day to see completed work.",
  "近 7 天完成": "Completed in 7 days",
  "课程与事项": "Classes & tasks",
  "活跃天数": "Active days",
  "最近 7 天": "Last 7 days",
  "晚于计划": "Completed late",
  "用于校准用时": "For better time estimates",
  "今天完成了什么": "Completed today",
  "{0} 项完成": "{0} completed",
  "这一天还没有完成记录": "No completion records for this day",
  "课程结束或完成日程、待办后，记录会出现在这里。": "Completed classes, events and tasks appear here.",
  "未按时": "Late",
  "按时": "On time",
  "{0}–{1} · {2} 分钟": "{0}–{1} · {2} min",
  "实际 {0} 分钟{1}": "Actual: {0} min{1}",
  " · 预计 {0} 分钟": " · Estimated: {0} min",
  "未记录实际用时": "Time spent not recorded",
  "查看待办事项 →": "View tasks →",
  "学习活动": "Learning activity",
  "按季度查看": "By quarter",
  "{0} 天活跃 · {1} 项完成": "{0} active days · {1} completed",
  "一": "M",
  "二": "T",
  "三": "W",
  "四": "T",
  "五": "F",
  "六": "S",
  "日": "S",
  "{0} · 完成 {1} 项": "{0} · {1} completed",
  "{0} 完成 {1} 项": "{0}: {1} completed",
  "少": "Less",
  "多": "More",
  "等待 AI 分析": "Waiting for AI analysis",
  "正在整理完整题目": "Organizing questions",
  "正在分析难度与知识点": "Analyzing difficulty and topics",
  "思考摘要": "Reasoning summary",
  "上次分析已中断，可重新分析。": "Last analysis was interrupted. Try again.",
  "重新分析": "Analyze again",
  "分析失败：{0}": "Analysis failed: {0}",
  "未知原因": "Unknown reason",
  "题目与知识点已整理": "Questions and topics ready",
  "尚未进行 AI 分析": "Not analyzed yet",
  "分析作业": "Analyze assignment",
  "整理结果暂不可用，请重新分析。": "Analysis unavailable. Try again.",
  "查看详情": "View details",
  "{0} 道题": "{0} questions",
  "题目显示失败，请关闭详情后重试。": "Could not show questions. Close details and try again.",
  "已标记错题 · 取消": "Marked incorrect · Undo",
  "标记为错题": "Mark incorrect",
  "Lab Sessions · 可选": "Labs · Optional",
  "{0} 份": "{0} files",
  "上传 PDF、Markdown 或 TXT 课件，AI 整理实验目标、步骤和提交要求；这里不记录错题。": "Upload PDF, Markdown or TXT. AI extracts lab goals, steps and submission requirements.",
  "这门课程还没有 Lab Session；没有实验课可以留空。": "No labs yet. Leave this empty if your course has none.",
  "{0} · {1} 个文件{2}{3}": "{0} · {1} files{2}{3}",
  " · 截止 {0}": " · Due {0}",
  " · 已归档": " · Archived",
  "正在提取课件文字": "Reading slides",
  "正在解析 Lab Session": "Analyzing lab",
  "上次解析已中断": "Last analysis was interrupted",
  "课件已解析": "Materials analyzed",
  "解析失败：{0}": "Analysis failed: {0}",
  "等待解析": "Waiting for analysis",
  "未导入：{0}": "Not imported: {0}",
  "查看解析内容": "View analysis",
  "无法显示解析内容：{0}": "Could not show analysis: {0}",
  "编辑信息": "Edit details",
  "解析课件": "Analyze materials",
  "移出归档": "Unarchive",
  "归档": "Archive",
  "删除 Lab Session": "Delete lab",
  "删除这份 Lab Session？": "Delete this lab?",
  "《{0}》的原文件会移入 Obsidian 回收站，解析内容转入隐藏的恢复目录。": "Source files for “{0}” move to Obsidian trash. Analysis moves to the recovery folder.",
  "确认删除": "Delete",
  "作业可整理题目并记录错题；Lab Session 可选，只解析课件。": "Organize assignment questions and errors. Optional labs extract material only.",
  "＋ 上传作业": "＋ Upload assignment",
  "＋ 上传 Lab Session": "＋ Upload lab",
  "← 返回课程概览": "← Course overview",
  "在用作业": "Active assignments",
  "已归档": "Archived",
  "还没有作业。上传后会保留原文件，复习时可按知识点选用。": "No assignments yet. Upload files to use their topics in review.",
  "暂无已归档的作业。": "No archived assignments.",
  "{0} · {1} 个文件": "{0} · {1} files",
  "截止 {0}": "Due {0}",
  "已同步到待办": "Linked to tasks",
  "难度 {0}/5": "Difficulty {0}/5",
  "暂无知识点": "No topics yet",
  "分析完成后显示知识点": "Topics appear after analysis",
  "部分文件导入失败：{0}": "Some imports failed: {0}",
  "文件导入中…": "Importing files…",
  "删除作业": "Delete assignment",
  "删除这份作业？": "Delete this assignment?",
  "《{0}》的原文件会移入 Obsidian 回收站，整理结果转入隐藏的恢复目录，关联待办和未完成的日程安排也会移除，已标记的错题记录也会移除。": "Source files for “{0}” move to Obsidian trash; analysis moves to recovery. Linked tasks, unfinished events and marked errors are removed.",
  "无法识别课程。": "Course not recognized.",
  "根据你确认的 Syllabus 解析结果整理。考核与日期请以原文件为准。": "Based on your confirmed syllabus analysis. Check assessments and dates against the source.",
  "上传 Syllabus 后，这里会展示课程简介、考核、日期、学习目标和知识结构。": "Upload a syllabus to see the course summary, assessments, dates, goals and topic map.",
  "↑ 更新 Syllabus": "↑ Update syllabus",
  "↑ 上传 Syllabus": "↑ Upload syllabus",
  "查看原文件": "View source",
  "打开整理笔记": "Open overview note",
  "从 Syllabus 开始认识这门课": "Start with the syllabus",
  "只会解析你通过上方入口新上传的文件；已有 Syllabus 笔记和左侧手写讲次不会被扫描或修改。": "Only newly uploaded files are analyzed. Existing syllabus notes and handwritten lessons are kept.",
  "上传并用 Codex 解析": "Upload and analyze",
  "项考核": "assessments",
  "个重要日期": "key dates",
  "个知识主题": "topics",
  "课程简介": "Course introduction",
  "这门课学什么": "What this course covers",
  "Syllabus 未提供课程内容简介。": "No introduction in the syllabus.",
  "课程主题": "Course topics",
  "成绩组成": "Grade breakdown",
  "考核结构": "Assessments",
  "Syllabus 未明确说明考核结构。": "Assessments are not specified in the syllabus.",
  "查看要求与评分细则": "View requirements and grading",
  "学期安排": "Semester plan",
  "重要日期": "Key dates",
  "Syllabus 未明确列出重要日期。": "No key dates listed in the syllabus.",
  "未注明": "Not specified",
  "课程脉络": "Course structure",
  "课程知识结构": "Topic map",
  "Syllabus 未列出可整理的知识主题。": "No topics listed in the syllabus.",
  "课程目标": "Course goals",
  "学习目标": "Learning goals",
  "Syllabus 未列出学习目标。": "No learning goals listed in the syllabus.",
  "复习参考": "Review reference",
  "考试范围": "Exam scope",
  "Syllabus 未明确说明考试范围。": "Exam scope is not specified in the syllabus.",
  "上传过的 Syllabus": "Uploaded syllabuses",
  "讲次由你在左侧单独维护；这里不会根据 Syllabus 生成或改写讲次。": "Manage lessons separately in the sidebar. Syllabus analysis does not create or edit lessons.",
  "← 课程概览": "← Course overview",
  "{0} 讲纳入学习范围 · 共 {1} 讲": "{0} lessons in scope · {1} total",
  "＋ 上传新讲课件": "＋ Upload new lesson",
  "当前讲次": "Current lesson",
  "已纳入学习范围": "In learning scope",
  "未纳入学习范围": "Outside learning scope",
  "上传课件并完成 Codex 分析后，这里会显示本讲简介。": "A lesson summary appears after uploading and analyzing slides.",
  "已确认": "Confirmed",
  "课堂学习": "Class learning",
  "确认日期": "Confirm date",
  "待确认": "To confirm",
  "/3 轮": "/3 rounds",
  "进入{0}": "Open {0}",
  "学习入口": "Learning tools",
  "双窗格预习": "Split preview",
  "课件与交互式预习并排": "Slides beside preview",
  "主笔记": "Main note",
  "打开本讲知识笔记": "Open lesson notes",
  "引导式回忆": "Guided recall",
  "先作答，再揭示与自评": "Answer, reveal, assess",
  "三轮递进 · 按日期解锁": "3 rounds · Unlock by date",
  "现在可以复习": "Ready to review",
  "预计 {0} 解锁": "Unlocks {0}",
  "学习完成后排期": "Scheduled after learning",
  "本讲课件": "Lesson slides",
  "＋ 上传课件": "＋ Upload slides",
  "还没有本讲课件。上传 PDF 后可直接用于双窗格预习。": "No slides yet. Upload a PDF to start split preview.",
  "管理当前讲次": "Manage lesson",
  "移出学习范围": "Remove from scope",
  "纳入学习范围": "Include in scope",
  "修改本讲标题": "Edit lesson title",
  "例如 动态规划与状态转移": "For example: Dynamic programming",
  "从上传这一讲的 PDF 课件开始。课件导入后会建立主笔记与预习工作区。": "Upload this lesson's PDF to create its main note and preview workspace.",
  "讲次导航": "Lesson navigation",
  "返回课程概览": "Course overview",
  "原有 Syllabus 笔记": "Original syllabus note",
  "原有课程目录": "Course directory",
  "学习范围": "Learning scope",
  "讲次总数": "Total lessons",
  "已纳入": "In scope",
  "待复习": "To review",
  "学习范围暂按讲次日期推定；三轮复习会在确认课堂学习和完成回忆后依次开放。": "Scope follows lesson dates. Review rounds unlock after class learning and recall.",
  "新建讲次并导入课件": "Create lesson and import slides",
  "讲次编号或名称": "Lesson number or name",
  "例如 L08": "For example: L08",
  "讲次名称请以 L01、L02 等编号开头": "Start the lesson name with L01, L02, etc.",
  "该讲次已存在，请改用“上传课件”": "Lesson already exists. Use Upload slides instead.",
  "课件导入失败：{0}": "Could not import slides: {0}",
  "已导入 {0} 份课件{1}": "Imported {0} slide files{1}",
  "；{0} 份失败：{1}": "; {0} failed: {1}",
  "课件已保存；预习内容未生成：{0}": "Slides saved; preview generation failed: {0}",
  "课件已导入；AI 预习内容目前支持文字版 PDF。": "Slides imported. AI preview currently supports text PDFs.",
  "课件已选择，但导入或草案生成未完成：{0}": "Import or generation did not finish: {0}",
  "找不到当前讲次": "Current lesson not found.",
  "当前讲次暂无 PDF；可先在课程概览上传。": "No PDF for this lesson. Upload one from the course page.",
  "讲次笔记不存在。": "Lesson note not found.",
  "课前预习": "Lesson preview",
  "第 {0} 轮复习": "Review round {0}",
  "← 返回当前讲次": "← Current lesson",
  "左侧查看 PDF，右侧逐项确认理解；过程仅保存在隐藏 JSON 中。": "Read slides alongside the preview and check each concept.",
  "先写出自己的答案，再揭示参考内容并自评。": "Write your answer, then reveal the reference and assess yourself.",
  "复习题先作答后揭示；本轮结果会用于后续复习与错误记录。": "Answer before revealing. Results guide later reviews and error records.",
  "摘要会在生成过程中更新": "Summary updates during generation",
  "{0} 份 PDF、{1} 页课件": "{0} PDFs · {1} pages",
  "{0} 份 PDF 课件": "{0} slide PDFs",
  "正在读取第 {0}/{1} 份：{2}": "Reading file {0}/{1}: {2}",
  "正在提取 PDF 文字…": "Extracting PDF text…",
  "已读取 {0}，等待 Codex 任务开始…": "Read {0}; waiting for Codex…",
  "已读取 {0}，正在连接 Codex…": "Read {0}; connecting to Codex…",
  "已读取 {0}，正在提交生成任务…": "Read {0}; submitting generation task…",
  "Codex 正在整理知识点、导图和分层知识块…": "Codex is organizing concepts and the topic map…",
  "Codex 正在分析课件；思考摘要持续更新…": "Codex is analyzing slides. The reasoning summary updates as it works…",
  "Codex 正在返回生成结果…": "Codex is returning results…",
  "正在校验并保存预习内容…": "Checking and saving preview…",
  " · 已送入 {0} 字符": " · {0} characters sent",
  "已用时 {0}{1} · {2} / {3}": "Elapsed {0}{1} · {2} / {3}",
  "1 份 PDF": "1 PDF",
  "{0} 份 PDF": "{0} PDFs",
  "正在提取课件文字…": "Reading slides…",
  "正在连接 Codex…": "Connecting to Codex…",
  "正在提交主笔记整理任务…": "Submitting note generation task…",
  "Codex 正在整理主笔记内容…": "Codex is organizing the main note…",
  "Codex 正在返回主笔记草案…": "Codex is returning a note draft…",
  "正在校验并保存主笔记草案…": "Checking and saving note draft…",
  "正在整理主笔记草案": "Drafting main note",
  "读取课件": "Read slides",
  "AI 整理": "AI analysis",
  "保存草案": "Save draft",
  "正在思考": "Thinking",
  "思考中": "Thinking",
  "正在生成这讲的预习内容": "Generating lesson preview",
  "AI 生成": "AI generation",
  "保存结果": "Save result",
  "预习内容还没有生成": "No preview yet",
  "上传文字版 PDF 后会自动分析并在这里显示总结、知识导图和知识块。": "Upload a text PDF to generate a summary, topic map and concepts.",
  "重新生成": "Generate again",
  "快速看懂这一讲": "Lesson at a glance",
  "重新分析课件": "Analyze slides again",
  "知识导图": "Topic map",
  "{0} 个主题 · {1} 个知识点": "{0} topics · {1} concepts",
  "分层知识块": "Concepts by topic",
  "＋ 补充": "＋ Add",
  "补充知识块": "Add concept",
  "所属主题": "Topic",
  "知识点名称": "Concept name",
  "解释（支持 Markdown）": "Explanation (Markdown)",
  "本讲要点": "Lesson highlights",
  "{0} / {1} 已检查": "{0} / {1} checked",
  "编辑知识块": "Edit concept",
  "哪里还不理解？写下疑问，后续复习会参考。": "What is unclear? Your questions will guide review.",
  "例如：这个公式为什么需要这个条件？": "For example: Why does this formula need this condition?",
  "理解了": "Understood",
  "没理解": "Unclear",
  "保存理解状态失败，请重试。": "Could not save understanding. Try again.",
  "预习已确认完成": "Preview complete",
  "完成理解检查": "Check your understanding",
  "确认后仍可继续修改这里的过程记录；主笔记始终是本讲唯一的正式 Markdown。": "You can edit these records after confirming. The main note remains the formal lesson note.",
  "已确认预习": "Preview confirmed",
  "确认完成预习": "Complete preview",
  "请先为每个知识块标记理解或疑问": "Mark every concept as understood or unclear first.",
  "确认预习完成": "Confirm preview",
  "已逐项检查本讲知识块，并记录不理解的地方。确认后会更新课程进度。": "Confirm that you checked every concept and recorded your questions. This updates course progress.",
  "唯一主笔记": "Main note",
  "重新生成草案": "Generate draft again",
  "AI 整理主笔记草案": "Draft main note with AI",
  "正在整理主笔记…": "Drafting main note…",
  "先检查草案，再追加到唯一主笔记；现有课堂批注不会被覆盖。": "Review the draft before appending. Existing notes and annotations are kept.",
  "追加到主笔记": "Append to main note",
  "写入主笔记": "Save to main note",
  "草案将直接写入现有「主笔记」部分；已有内容与批注会保留。": "The draft appends to the Main note section. Existing content and annotations are kept.",
  "确认写入": "Save",
  "主笔记已建立。接下来可以在 Markdown 中继续批注与补充课堂内容。": "Main note created. Continue adding class notes in Markdown.",
  "确认预习后，可从课件与疑问整理一份主笔记草案。": "After preview, generate a main note draft from slides and questions.",
  "本讲 PDF 课件 · {0} 份": "Lesson PDFs · {0} files",
  "尚未上传 PDF 课件": "No PDF uploaded",
  "切换左侧 PDF 课件": "Switch slide PDF",
  "打开主笔记 ↗": "Open main note ↗",
  "引导问题": "Guided questions",
  "核心提取与薄弱点": "Core concepts & weak points",
  "方法选择与应用": "Method selection & application",
  "跨讲次混合练习": "Mixed practice across lessons",
  "AI 生成问题草案": "Draft questions with AI",
  "正在生成问题…": "Generating questions…",
  "＋ 添加问题": "＋ Add question",
  "添加复习问题": "Add review question",
  "问题": "Question",
  "参考答案（可稍后补充）": "Reference answer (optional)",
  "对应讲次（可选）": "Related lesson (optional)",
  "当前讲次或其他讲次路径": "Path to this or another lesson",
  "待确认的 AI 问题 · {0} 道": "Review AI questions · {0} questions",
  "参考：{0}": "Reference: {0}",
  "采用这些问题": "Use these questions",
  "采用 AI 问题": "Use AI questions",
  "将这些问题加入当前回忆或复习；作答前参考答案仍会隐藏。": "Add these questions to recall or review. Answers stay hidden until you respond.",
  "确认采用": "Use questions",
  "还没有问题。可以让 AI 生成草案，或手动添加。": "No questions yet. Generate a draft with AI or add your own.",
  "参考作业 · {0} · {1}": "Assignment reference · {0} · {1}",
  "作业": "Assignment",
  "知识点": "Topics",
  "已记录 · {0}": "Recorded · {0}",
  "会": "Confident",
  "不确定": "Unsure",
  "不会": "Need practice",
  "先写下自己的答案": "Write your answer first",
  "先独立回忆，不要查看主笔记。": "Recall independently before reading the main note.",
  "参考内容": "Reference",
  "参考答案尚未准备；先根据自己的理解自评，AI 内容接入后再补充。": "No reference answer yet. Assess your understanding for now.",
  "我已作答 · 查看参考内容": "Reveal reference",
  "请先写下自己的答案": "Write your answer first.",
  "本轮已完成": "Round complete",
  "完成引导式回忆": "Complete guided recall",
  "完成第 {0} 轮复习": "Complete review {0}",
  "结果已保存在隐藏 JSON 中。": "Your results have been saved.",
  "所有题目都完成自评后，才可以确认结束。": "Assess every answer before completing this round.",
  "确认本轮完成": "Complete round",
  "请先完成每道题的作答与自评": "Answer and assess every question first.",
  "确认回忆完成": "Confirm recall",
  "确认第 {0} 轮复习": "Confirm review {0}",
  "确认所有题目已经先作答、再查看参考内容并完成自评。薄弱点会保存在 Error Log 中。": "Confirm you answered, revealed the reference and assessed every question. Weak points go to the error log.",
  "复习轮次无效。": "Invalid review round.",
  "待排期": "Not scheduled",
  "本轮尚未解锁": "Round locked",
  "先确认课堂学习，才能建立复习日期。": "Confirm class learning to set review dates.",
  "先完成引导式回忆，再开始间隔复习。": "Complete guided recall before spaced review.",
  "先完成上一轮复习。": "Complete the previous round first.",
  "预计 {0} 解锁。": "Unlocks {0}.",
  "建议 {0} · {1} 到期": "Suggested {0} · Due {1}",
  "参考作业": "Assignment references",
  "按标注知识点出引导题 · 原件可打开": "Generate guided questions from topics, or open originals",
  "还没有可参考的作业。": "No assignments available for reference.",
  "打开作业档案 →": "Open assignments →",
  "难度 {0}/5 · {1}{2}": "Difficulty {0}/5 · {1}{2}",
  "未标注知识点": "No topics marked",
  "已用于本轮": "Used in this round",
  "AI 根据作业出题": "Generate from assignment",
  "已导入 {0} 份课件到 {1}{2}": "Imported {0} files into {1}{2}",
  "《{0}》预习内容已生成。": "Preview for “{0}” is ready.",
  "主笔记草案已生成，请核对后写入。": "Main note draft ready. Review it before saving.",
  "问题草案已生成，请核对后采用。": "Question draft ready. Review it before use.",
  "创建学期": "Create semester",
  "学期名称": "Semester name",
  "例如：26 Fall 或 2027 Spring": "For example: 26 Fall or 2027 Spring",
  "创建学期失败，请重试": "Could not create semester. Try again.",
  "为学期创建课程": "Create course",
  "所属学期": "Semester",
  "课程代码": "Course code",
  "例如：COMP 1002": "For example: COMP 1002",
  "课程名称": "Course name",
  "例如：Machine Learning": "Courses already in another semester share their files and learning records.",
  "若相同课程已存在于其他学期，会复用原课程文件与学习记录。": "Create course",
  "创建课程": "Create course",
  "创建课程失败：{0}": "Could not create course: {0}",
  "Learning Hub · AI 与日程": "Learning Hub · Settings",
  "所有 DeepSeek 功能共用此 API Key；接口地址和默认模型供学习助手、待办对话与日程等通用功能使用。": "All DeepSeek features share this API key. The common endpoint and default model are used by the assistant, task intake and scheduling.",
  "Codex 在本机以只读方式生成草案。预习和日程只有在你确认后才写入学习数据。": "Manage your workspace, AI tools and schedule. Review AI drafts before saving.",
  "Codex 程序": "Codex executable",
  "本机 codex 可执行文件的绝对路径。": "Absolute path to the local Codex executable.",
  "连接与模型列表": "Connection & models",
  "读取本机 Codex 可用模型，不会发起模型推理。": "Fetch available models without running inference.",
  "读取可用模型": "Load models",
  "已读取 {0} 个模型": "Loaded {0} models.",
  "Codex 连接失败：{0}": "Codex connection failed: {0}",
  "模型": "Model",
  "留空使用 Codex 当前默认模型。实际测试建议选 Luna 轻量模型。": "Leave empty to use the current Codex default.",
  "Codex 默认": "Codex default",
  "{0}（已保存）": "{0} (saved)",
  "思考强度": "Reasoning effort",
  "选项由所选模型提供；留空使用该模型默认值。": "Options come from the selected model. Leave empty for its default.",
  "模型默认": "Model default",
  "Codex 并行任务数": "Concurrent tasks",
  "同时运行独立的 Codex 生成任务；默认 2，最多 4，超出的任务会排队。": "Run up to 4 Codex tasks at once. Additional tasks queue. Default: 2.",
  "{0} 个任务": "{0} tasks",
  "AI 生成语言": "AI content language",
  "用于预习、主笔记、回忆与复习问题、Lab Session 解析及 AI 日程摘要；已有内容不会自动翻译。": "Language for new previews, notes, questions, labs and schedule summaries. Existing content is kept.",
  "中文（默认）": "Chinese (default)",
  "PDF 文本工具": "PDF text extractor",
  "可选。留空时自动查找 pdftotext；扫描版 PDF 需先 OCR。": "Optional. Finds pdftotext automatically. Scan PDFs need OCR first.",
  "自动查找": "Auto-detect",
  "DeepSeek API · 全插件共用": "DeepSeek API",
  "学习助手、待办对话、可学习时间设置、草稿标题和其他 DeepSeek 功能统一使用这里的地址与密钥。新功能也应从同一配置入口发起。": "Shared by the assistant, task intake, study availability and rest settings, draft naming and other DeepSeek features.",
  "API 地址": "API endpoint",
  "填写完整的 HTTPS chat/completions 地址；默认使用 DeepSeek 官方接口。": "Full HTTPS chat/completions URL. Uses DeepSeek by default.",
  "由本插件的 DeepSeek 功能共用；只在你主动使用相关 AI 功能时发送。": "Shared by DeepSeek features. Sent only when you use AI.",
  "默认模型": "Default model",
  "默认思考强度": "Default reasoning",
  "快速模式适合基础解释；复杂问题可在侧边栏随时切换到思考模式。": "Use fast mode for simple questions. Switch modes in the assistant.",
  "关闭 · 快速": "Off · Fast",
  "低": "Low",
  "高": "High",
  "最大": "Maximum",
  "草稿本 · Instant Draft": "Drafts",
  "新建时间草稿后立即在 Obsidian 中打开。关闭草稿时，可使用上方统一的 DeepSeek 配置自动生成标题；空草稿保持时间标题。": "New drafts open immediately. Closing a draft can generate a title with DeepSeek.",
  "关闭草稿后自动命名": "Name drafts on close",
  "只处理 Draft 文件夹中仍以时间命名且有正文的草稿。": "Only nonempty timestamped notes in the Draft folder are renamed.",
  "学期与课程": "Semesters & courses",
  "左侧课程列表和主页课程总览会显示所选学期。现有课程资料和学习记录保持原路径。": "Navigation and the home page show the selected semester.",
  "当前学期": "Current semester",
  "切换左侧课程分组与主页课程总览显示的范围。": "Choose the courses shown in navigation and on the home page.",
  "{0} · {1} 门课程": "{0} · {1} courses",
  "新建学期": "New semester",
  "例如 26 Fall、27 Spring；新学期会自动切换为当前学期。": "For example: 26 Fall or 27 Spring. New semesters become active.",
  "＋ 创建学期": "＋ Create semester",
  "为 {0} 创建课程": "Create course for {0}",
  "输入课程代码和名称；可在弹窗中选择要归属的学期。": "Enter a course code and name. Choose its semester in the dialog.",
  "＋ 创建课程": "＋ Create course",
  "只读同步日历事件，用于主页、完整日程和 AI 排程冲突检查。授权凭证保存在本 vault 的插件数据中；若同步 vault，凭证也会同步。": "Read-only event sync for schedules and conflict checks. Credentials are stored in this vault and follow vault sync.",
  "没有 Client ID？按照 ": "Need a Client ID? Follow ",
  "Google 官方桌面应用设置说明": "Google's desktop setup guide",
  " 创建即可。": " to create one.",
  "桌面应用 Client ID": "Desktop client ID",
  "先在 Google Cloud 为自己的项目启用 Calendar API，并创建「桌面应用」OAuth 客户端。": "Enable Calendar API in Google Cloud and create a Desktop app OAuth client.",
  "Client Secret（按客户端要求）": "Client secret (if required)",
  "部分桌面客户端会要求此项；若授权报 client_secret is missing，请填写创建客户端时提供的 Secret。": "Enter the secret from your OAuth client if authorization requires it.",
  "已连接 · 同步失败：{0}": "Connected · Sync failed: {0}",
  "已连接 · 上次同步 {0}": "Connected · Last sync {0}",
  "已连接 · 尚未同步": "Connected · Not synced yet",
  "连接失败：{0}": "Connection failed: {0}",
  "尚未连接": "Not connected",
  "连接状态": "Connection status",
  "连接 Google Calendar": "Connect Google Calendar",
  "Google Calendar 已连接，找到 {0} 个日历。": "Google Calendar connected. Found {0} calendars.",
  "Google Calendar 连接失败：{0}": "Google Calendar connection failed: {0}",
  "立即同步": "Sync now",
  "断开": "Disconnect",
  "主日历": "Primary calendar",
  "请至少保留一个日历。": "Keep at least one calendar selected.",
  "日历同步失败：{0}": "Calendar sync failed: {0}",
  "可学习时间": "Study availability",
  "＋ 添加可用时段": "＋ Add time window",
  "手动录入课程、会议等固定时段；AI 排程会避开它们。": "Add classes, meetings or other fixed events. AI schedules around them.",
  "＋ 添加固定安排": "＋ Add fixed event",
  "可用时段 {0}": "Time window {0}",
  "安排名称": "Event name",
  "删除": "Delete",
  "学习助手": "Learning assistant",
  "历史对话": "Chat history",
  "新对话": "New chat",
  "{0} 条": "{0} chats",
  "还没有历史对话。": "No chat history yet.",
  "未开始": "Not started",
  "选择对话": "Choose chat",
  "DeepSeek 模型": "DeepSeek model",
  "未关联页面": "No page linked",
  "当前页面自动附上": "Current page attached",
  "打开笔记或课件后自动附上": "Open a note or slides to attach context",
  "选中 {0} 字": "{0} characters selected",
  "从当前内容开始提问": "Ask about the current content",
  "可解释选中内容、梳理概念或继续追问。课程、讲次和笔记会随每次提问附上。": "Explain a selection, clarify a concept or ask a follow-up. Course and lesson context travels with your question.",
  "正在思考并整理回答…": "Preparing an answer…",
  "移除 {0}": "Remove {0}",
  "提问，输入 @ 引用文件…": "Ask a question. Type @ to attach a file…",
  "先在插件设置中填写 DeepSeek API Key…": "Add a DeepSeek API key in settings first…",
  "向学习助手提问": "Ask the learning assistant",
  "当前页面 · 选中内容 · @文件": "Current page · Selection · @Files",
  "处理中…": "Working…",
  "前往设置添加 API Key →": "Add API key in settings →",
  "请从 @ 搜索结果中选中文件后再发送。": "Choose a file from the @ results before sending.",
  "当前页面未附上：{0}": "Current page was not attached: {0}",
  "已将明确的理解错误加入 Error Log。": "Added the identified misconception to the error log.",
  "学习助手：{0}": "Learning assistant: {0}",
  "未提供": "Unavailable",
  "缓存写入": "Cache write",
  "输入 {0} · 缓存命中 {1} · {2} {3} · 输出 {4}（推理 {5}） · 总计 {6}": "Input {0} · Cache hit {1} · {2} {3} · Output {4} (reasoning {5}) · Total {6}",
  "Codex 本次没有返回 token 用量数据。": "Codex returned no token usage data.",
  "本次：{0}": "This turn: {0}",
  "线程累计：{0}": "Thread total: {0}",
  "模型上下文窗口 {0} tokens": "Context window {0} tokens",
  "Codex 用量｜{0}": "Codex usage | {0}",
  "DeepSeek 本次未返回 token 用量数据。": "DeepSeek returned no token usage data.",
  "DeepSeek 用量｜{0}": "DeepSeek usage | {0}",
  "缓存未命中": "Cache miss",
  "已逾期 · ": "Overdue · ",
  "今天 · ": "Today · ",
  "明天 · ": "Tomorrow · ",
  "即将截止 · ": "Due soon · ",
  "界面与语言": "Interface & language",
  "选择界面语言，页面和设置会立即更新。笔记与已有 AI 内容保留原文。": "Change interface language instantly. Notes and existing AI content keep their original text.",
  "界面语言": "Interface language",
  "中文或 English；切换后立即生效。": "Chinese or English. Updates immediately.",
  "Codex · 本地生成": "Codex · Local generation",
  "插件设置": "Plugin settings",
  "开始时间": "Start time",
  "结束时间": "End time",
  "星期": "Weekday",
  "结束时间应晚于开始时间": "End time must be later than start time.",
  "周日": "Sunday",
  "周一": "Monday",
  "周二": "Tuesday",
  "周三": "Wednesday",
  "周四": "Thursday",
  "周五": "Friday",
  "周六": "Saturday",
  "待预习": "To preview",
  "待学习": "To learn",
  "快速": "Fast",
  "思考 · 低": "Thinking · Low",
  "思考 · 高": "Thinking · High",
  "思考 · 最大": "Thinking · Maximum",
  "01 · 初次巩固": "01 · Consolidation",
  "02 · 应用检验": "02 · Application",
  "03 · 混合迁移": "03 · Transfer",
  "核心概念与薄弱点": "Core concepts & weak points",
  "提取、方法选择与应用": "Recall, methods & application",
  "跨讲次联系与综合题": "Connections & mixed practice",
  "5–10 分钟": "5–10 min",
  "约 15 分钟": "About 15 min",
  "约 20 分钟": "About 20 min",
  "LEARNING SPACE": "LEARNING SPACE",
  "COURSE SPACE": "COURSE SPACE",
  "PERSONAL SPACE": "PERSONAL SPACE",
  "COURSE INITIALIZATION · CODEX": "COURSE SETUP · CODEX",
  "DRAFTS / RECENT NOTES": "DRAFTS / RECENT NOTES",
  "SCHEDULE": "SCHEDULE",
  "TO DO": "TASKS",
  "LEARNING REVIEW": "LEARNING REVIEW",
  "DAY IN REVIEW": "DAY IN REVIEW",
  "ACTIVITY": "ACTIVITY",
  "{0} / MATERIALS": "{0} / MATERIALS",
  "COURSE OVERVIEW / {0}": "COURSE OVERVIEW / {0}",
  "LECTURE SPACE / {0}": "LECTURE SPACE / {0}",
  "QUESTION {0}": "QUESTION {0}",
  "LEARNING SPACE / AI": "LEARNING SPACE / AI",
  "置顶此项": "Pin",
  "课程路径已被同名文件占用：{0}": "Course path is occupied by a file: {0}",
  "Syllabus 目前支持 PDF、Markdown 和 TXT。": "Syllabus supports PDF, Markdown and TXT.",
  "找不到这门课程。": "Course not found.",
  "请选择通过课程页上传的 Syllabus。": "Choose a syllabus uploaded from the course page.",
  "找不到上传的 Syllabus 原文件。": "Uploaded syllabus not found.",
  "不支持这种 Syllabus 文件格式。": "Unsupported syllabus format.",
  "Syllabus 没有可读取的文字。扫描版 PDF 需要先 OCR。": "No readable text in the syllabus. Scan PDFs need OCR.",
  "Syllabus 原文件已不存在。": "Syllabus source no longer exists.",
  "无法解析「{0}」：{1}": "Could not read “{0}”: {1}",
  "Lab Session 没有可提取的文字；扫描版 PDF 需要先 OCR。": "No readable lab text. Scan PDFs need OCR.",
  "作业截止日期无效。": "Invalid assignment deadline.",
  "作业已不存在。": "Assignment no longer exists.",
  "找不到这道题。": "Question not found.",
  "暂不支持读取 {0} 文件作为对话上下文。": "Cannot use {0} files as chat context.",
  "Google 未返回持续授权，请重新连接并允许离线访问。": "Google did not return offline access. Reconnect and allow it.",
  "Codex 连接需要本地 Obsidian vault。": "Codex needs a local Obsidian vault.",
  "本讲尚无 PDF 课件。": "No PDF slides for this lesson.",
  "课件「{0}」解析失败：{1}": "Could not read slides “{0}”: {1}",
  "这讲课件正在解析，请稍候。": "Lesson analysis is in progress. Please wait.",
  "主笔记正在整理，请稍候。": "Main note generation is in progress. Please wait.",
  "先完成预习理解检查，再整理主笔记。": "Complete the preview check before generating a main note.",
  "主笔记已经生成，请直接在原 Markdown 中继续完善。": "Main note already exists. Continue editing it in Markdown.",
  "本轮复习尚未解锁。": "This review round is locked.",
  "引用文件已不存在：{0}": "Referenced file no longer exists: {0}",
  "AI 未返回有效标题": "AI did not return a valid title.",
  "Codex 连接已关闭。": "Codex connection is closed.",
  "Codex 工作目录必须是本地 vault 的绝对路径。": "Codex working directory must be an absolute local vault path.",
  "无法启动 Codex：{0}": "Could not start Codex: {0}",
  "Codex 连接中断（{0}）。": "Codex connection interrupted ({0}).",
  "Codex 返回了无效的模型列表。": "Codex returned an invalid model list.",
  "Codex 请求缺少提示内容。": "Codex request has no prompt.",
  "Codex 请求缺少 JSON 输出结构。": "Codex request has no JSON schema.",
  "Codex 未返回会话 ID。": "Codex returned no session ID.",
  "Codex 生成超过 {0} 分钟，请重试。": "Codex generation exceeded {0} min. Try again.",
  "Codex 未返回符合 JSON 格式的草案。": "Codex returned no valid JSON draft.",
  "Codex 尚未启动。": "Codex has not started.",
  "Codex 请求超时：{0}": "Codex request timed out: {0}",
  "Codex 输入管道已关闭。": "Codex input pipe is closed.",
  "Codex 协议消息无效：{0}": "Invalid Codex protocol message: {0}",
  "Codex 请求失败。": "Codex request failed.",
  "Codex 生成未完成（{0}）。": "Codex generation did not finish ({0}).",
  "Codex 未返回草案内容。": "Codex returned no draft content.",
  "Codex 没有返回课程初始化内容。": "Codex returned no course overview.",
  "Codex 没有从 Syllabus 提取到可用的课程信息。": "Codex found no usable course information in the syllabus.",
  "DeepSeek API 地址无效，请填写完整的 HTTPS chat/completions 地址。": "Invalid DeepSeek endpoint. Enter a full HTTPS chat/completions URL.",
  "DeepSeek API 地址必须使用 HTTPS，且不能包含账号、密码或片段。": "DeepSeek URL must use HTTPS, without credentials or fragments.",
  "请输入问题。": "Enter a question.",
  "不支持的 DeepSeek 模型。": "Unsupported DeepSeek model.",
  "缺少对话消息。": "Chat messages are missing.",
  "不支持的思考强度。": "Unsupported reasoning effort.",
  "DeepSeek API Key 无效或没有访问权限。": "DeepSeek API key is invalid or has no access.",
  "DeepSeek 账户余额不足。": "Insufficient DeepSeek balance.",
  "DeepSeek 请求过于频繁，请稍后重试。": "Too many DeepSeek requests. Try again later.",
  "DeepSeek 服务暂时不可用，请稍后重试。": "DeepSeek is unavailable. Try again later.",
  "DeepSeek 请求失败（HTTP {0}）。": "DeepSeek request failed (HTTP {0}).",
  "DeepSeek 需要 Obsidian requestUrl 或等效请求函数。": "DeepSeek needs Obsidian requestUrl or an equivalent request function.",
  "请先在设置中填写 DeepSeek API Key。": "Add a DeepSeek API key in settings first.",
  "无法连接 DeepSeek，请检查网络连接。": "Could not connect to DeepSeek. Check your network.",
  "回答被模型的输出 token 预算截断；提高输出 token 预算后再试。": "The answer reached the output token limit. Increase the limit and retry.",
  "DeepSeek 未返回可显示的回答。": "DeepSeek returned no answer.",
  "Google 授权已失效，请重新连接。": "Google authorization expired. Reconnect.",
  "Google 拒绝了本次授权码（invalid_grant），请重新连接。": "Google rejected the authorization code (invalid_grant). Reconnect.",
  "此 OAuth 客户端要求 Client Secret，请在 Learning Hub 设置中填写后重试（HTTP 400 · invalid_request）。": "This OAuth client requires a secret. Add it in settings and retry (HTTP 400 · invalid_request).",
  "Google 授权失败（HTTP {0}{1}）。": "Google authorization failed (HTTP {0}{1}).",
  "未知": "Unknown",
  "Google Calendar 连接缺少请求或浏览器接口": "Google Calendar requires request and browser interfaces.",
  "请填写 Google Cloud 桌面应用的 OAuth Client ID。": "Enter your Google Cloud desktop OAuth client ID.",
  "Google 授权状态不匹配。": "Google authorization state did not match.",
  "无法启动本机授权回调：{0}": "Could not start the local authorization callback: {0}",
  "Google 授权等待超时，请重试。": "Google authorization timed out. Try again.",
  "无法打开系统浏览器：{0}": "Could not open your browser: {0}",
  "请先连接 Google Calendar。": "Connect Google Calendar first.",
  "Google 授权缺少刷新凭证，请重新连接。": "Google returned no refresh token. Reconnect.",
  "Google Calendar 读取失败（HTTP {0}）。": "Could not read Google Calendar (HTTP {0}).",
  "作业没有可提取的文字；扫描版 PDF 请先 OCR。": "No readable assignment text. Scan PDFs need OCR first.",
  "AI 未能整理出完整的作业题目。": "AI could not extract complete assignment questions.",
  "AI 返回的作业难度无效。": "AI returned an invalid difficulty.",
  "AI 未返回可用的作业知识点。": "AI returned no usable assignment topics.",
  "AI 未返回可用的 Lab Session 解析内容。": "AI returned no usable lab analysis.",
  "PDF 文本工具路径无效。": "Invalid PDF extractor path.",
  "找不到 PDF 文本工具。请在插件设置中填写 pdftotext 的绝对路径。": "PDF text extractor not found. Set the absolute pdftotext path in settings.",
  "只能从本地 PDF 课件提取文字。": "Text can only be extracted from local PDFs.",
  "无法读取课件文字：{0}": "Could not read slide text: {0}",
  "课件没有可提取的文字。扫描版 PDF 需要先进行 OCR。": "No readable slide text. Scan PDFs need OCR first.",
  "没有可解析的 PDF 课件。": "No PDF slides to analyze.",
  "预习内容格式无效。": "Invalid preview format.",
  "预习内容标题或知识点不足，请重试。": "Preview title or concepts are missing. Try again.",
  "无效的排程起始日期": "Invalid schedule start date.",
  "{0}必须是时间段列表": "{0} must be a list of time blocks.",
  "{0}第 {1} 项时间无效": "Invalid time in {0}, item {1}.",
  "{0}第 {1} 项日期无效": "Invalid date in {0}, item {1}.",
  "请填写有效的排程起始日期": "Enter a valid schedule start date.",
  "排程天数必须在 1 到 {0} 之间": "Schedule length must be between 1 and {0} days.",
  "请先在完整日程中设置可学习时间": "Set study availability from the full schedule first.",
  "所选日期内没有可用时间": "No available time in the selected dates.",
  "缺少排程请求上下文": "Schedule request context is missing.",
  "日程草案存在冲突，不能确认": "Schedule draft has conflicts and cannot be applied.",
  "缺少排程日期范围": "Schedule date range is missing.",
  "主笔记草案格式无效。": "Invalid main note draft format.",
  "主笔记草案为空，请重试。": "Main note draft is empty. Try again.",
  "问题草案格式无效。": "Invalid question draft format.",
  "问题草案内容不足，请重试。": "Question draft is incomplete. Try again.",
  "AI 返回的事项格式不完整，请再试一次。": "AI task format is incomplete. Try again.",
  "AI 没有返回可核对的事项列表。": "AI returned no task list to review.",
  "一次最多整理 30 项待办，请分批添加。": "Limit: 30 tasks at a time. Add them in batches.",
  "AI 返回了无效的事项，请再试一次。": "AI returned an invalid task. Try again.",
  "默认强度": "Default effort",
  "生成失败：{0}。{1}": "Generation failed: {0}. {1}",
  "生成失败：{0}": "Generation failed: {0}",
  "这份课件较长；可降低 Codex 思考强度后重试。": "These slides are long. Try a lower reasoning effort.",
  "请检查 PDF 文字或 AI 设置后重试。": "Check PDF text and AI settings, then retry." ,
  "完成作业：{0}": "Complete assignment: {0}",
  "{0} · 预习": "{0} · Preview",
  "下一次 Lec": "Next lecture",
  "{0} · 第 {1} 轮复习": "{0} · Review {1}",
  "间隔复习": "Spaced review",
  "DeepSeek 对话": "DeepSeek chat"
,
  "截止": "Due",
  '按现价约 ¥{0}': 'At current rates ≈ ¥{0}',
  '请填写有效日期，年份须为四位数，并补全月份和日期。': 'Enter a valid date with a four-digit year, month and day.',
  '上一份课件': 'Previous slide file',
  '下一份课件': 'Next slide file',
  '第 {0} / {1} 份': 'File {0} of {1}',
  '无法打开课件：{0}': 'Could not open slides: {0}',
  '切换左侧阅读的课件；预习内容综合本讲全部课件。': 'Switch the slides on the left. Preview covers all files in this lesson.',
};
