"""Bundle the maintainable source modules into Obsidian's single main.js entrypoint."""

from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent
MODULES = ('local-storage', 'ui-strings', 'ui-copy', 'i18n', 'codex-client', 'token-usage', 'generation-language', 'date-input', 'lecture-ai', 'course-initial', 'homework-ai', 'lab-ai', 'chat-error-ai', 'preview-structure', 'schedule-ai', 'planning', 'task-views', 'task-intake', 'study-availability', 'study-ai', 'deepseek-stream', 'deepseek-pricing', 'deepseek-chat', 'chat-context', 'chat-store', 'chat-view', 'google-calendar', 'semesters', 'drafts', 'settings', 'feature-bridge', 'study-progress', 'study-reader', 'vault-guide')


def build():
    pieces = [
        '// Generated by build.py. Edit plugin.js and modules/*.js instead.\n',
        '(function(module, require) {\n',
        'const __lhFactories = {\n',
    ]
    for name in MODULES:
        source = (ROOT / 'modules' / f'{name}.js').read_text()
        pieces.append(f'  {json.dumps(f"./modules/{name}")}: function(module, exports, require) {{\n{source}\n  }},\n')
    pieces.extend([
        '};\n',
        'const __lhCache = Object.create(null);\n',
        'const __lhNativeRequire = require;\n',
        "function __lhRequire(id) {\n",
        "  if (id.startsWith('./') && !id.startsWith('./modules/') && Object.prototype.hasOwnProperty.call(__lhFactories, './modules/' + id.slice(2))) id = './modules/' + id.slice(2);\n",
        '  if (!Object.prototype.hasOwnProperty.call(__lhFactories, id)) return __lhNativeRequire(id);\n',
        '  if (!__lhCache[id]) { const local = { exports: {} }; __lhCache[id] = local; __lhFactories[id](local, local.exports, __lhRequire); }\n',
        '  return __lhCache[id].exports;\n',
        '}\n',
        '(function(module, require) {\n',
        (ROOT / 'plugin.js').read_text(),
        '\n})(module, __lhRequire);\n',
        '})(module, require);\n',
    ])
    dist = ROOT / 'dist'
    dist.mkdir(exist_ok=True)
    output = dist / 'main.js'
    output.write_text(''.join(pieces))
    (ROOT / 'main.js').write_text(output.read_text())
    return output


if __name__ == '__main__':
    print(build())
